services:
  devsnap-db:
    container_name: devsnap-db
    image: postgres:17
    environment:
      POSTGRES_USER: devsnap_user
      POSTGRES_PASSWORD: devsnap_password
      POSTGRES_DB: devsnap_db
    ports:
      - '5434:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
