spring.application.name=devsnap
spring.datasource.url=jdbc:postgresql://localhost:5434/devsnap_db
spring.datasource.username=devsnap_user
spring.datasource.password=devsnap_password
spring.jpa.hibernate.ddl-auto=update